version: '3'

services:
  web:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: puma
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: postgres://postgres@db
      REDIS_URL: redis://redis@redis
  db:
    image: postgres:11-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:4.0.10-alpine3.8
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - .${PWD}/redis.conf:/usr/local/etc/redis/redis.conf
